# Generated by Django 4.2.7 on 2023-11-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0002_administrativeboundary_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministrativeBoundary',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='userdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='opt_in_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
