# Generated by Django 4.2.7 on 2023-11-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0003_delete_administrativeboundary_delete_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
