# Generated by Django 4.2.7 on 2023-11-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0004_alter_userdata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
