# Generated by Django 4.2.7 on 2023-11-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0005_alter_userdata_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='location',
        ),
        migrations.AddField(
            model_name='userdata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
