# Generated by Django 4.2.7 on 2023-11-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0006_remove_userdata_location_userdata_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='latitude',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='longitude',
        ),
    ]
