# Generated by Django 4.2.7 on 2024-01-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0008_userdata_latitude_userdata_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainGaugeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('raingauge_measurement', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
