# Generated by Django 4.2.7 on 2024-01-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0009_raingaugedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RainGaugeData',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='emergency_contact_phone',
        ),
    ]
