# Generated by Django 4.2.7 on 2024-01-18 19:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0010_delete_raingaugedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBoundaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_0', models.BigIntegerField()),
                ('iso', models.CharField(max_length=3)),
                ('name_0', models.CharField(max_length=75)),
                ('id_1', models.BigIntegerField()),
                ('name_1', models.CharField(max_length=75)),
                ('id_2', models.BigIntegerField()),
                ('name_2', models.CharField(max_length=75)),
                ('id_3', models.BigIntegerField()),
                ('name_3', models.CharField(max_length=75)),
                ('id_4', models.BigIntegerField()),
                ('name_4', models.CharField(max_length=100)),
                ('id_5', models.BigIntegerField()),
                ('name_5', models.CharField(max_length=75)),
                ('type_5', models.CharField(max_length=25)),
                ('engtype_5', models.CharField(max_length=25)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
