# Generated by Django 4.2.7 on 2024-01-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0011_adminboundaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_data_country', to='EWS.adminboundaries'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_data_county', to='EWS.adminboundaries'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_data_sub_county', to='EWS.adminboundaries'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='sub_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_data_sub_location', to='EWS.adminboundaries'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EWS.adminboundaries'),
        ),
    ]
