# Generated by Django 4.2.7 on 2024-01-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0012_userdata_country_userdata_county_userdata_sub_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_data_location', to='EWS.adminboundaries'),
        ),
    ]
