# Generated by Django 4.2.7 on 2024-01-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0013_alter_userdata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
