# Generated by Django 4.2.7 on 2024-01-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0014_alter_userdata_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminboundaries',
            name='engtype_5',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='id_0',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='id_2',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='id_3',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='id_4',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='id_5',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='type_5',
        ),
    ]
