# Generated by Django 4.2.7 on 2024-01-23 11:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0015_remove_adminboundaries_engtype_5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminboundaries',
            name='name_0',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='name_3',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='name_4',
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='name_5',
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='country',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='country_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='county',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='county_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='iso',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='locat_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='sb_cnt_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='sb_loca_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='sub_cnty',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='sub_locat',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
