# Generated by Django 4.2.7 on 2024-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0018_alter_userdata_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminboundaries',
            options={'ordering': ['county', 'sub_cnty', 'location', 'sub_locat']},
        ),
        migrations.RemoveField(
            model_name='adminboundaries',
            name='id',
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='custom_primary_key',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
