# Generated by Django 4.2.7 on 2024-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0019_alter_adminboundaries_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminboundaries',
            name='custom_primary_key',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
