# Generated by Django 4.2.7 on 2024-03-12 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0020_alter_adminboundaries_custom_primary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminboundaries',
            name='custom_primary_key',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.AddField(
            model_name='adminboundaries',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
