# Generated by Django 4.2.7 on 2024-03-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0021_remove_adminboundaries_custom_primary_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
