# Generated by Django 4.2.7 on 2024-04-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('EWS', '0022_alter_userdata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='opt_in_alerts',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_county', to='EWS.adminboundaries'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='groups',
            field=models.ManyToManyField(related_name='User_Data', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_location', to='EWS.adminboundaries'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sub_county', to='EWS.adminboundaries'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sub_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sub_location', to='EWS.adminboundaries'),
        ),
    ]
