# Generated by Django 4.2.7 on 2024-04-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0023_remove_userdata_opt_in_alerts_alter_userdata_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='location',
        ),
    ]
