# Generated by Django 4.2.7 on 2024-04-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0024_remove_userdata_country_remove_userdata_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='county',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sub_county',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sub_location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
