# Generated by Django 4.2.7 on 2024-04-22 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0025_userdata_location_alter_userdata_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_county', to='EWS.adminboundaries'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_location', to='EWS.adminboundaries'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sub_county', to='EWS.adminboundaries'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sub_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sub_location', to='EWS.adminboundaries'),
        ),
    ]
