# Generated by Django 4.2.7 on 2024-05-11 14:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0026_alter_userdata_county_alter_userdata_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminboundaries',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(max_length=50, null=True, srid=4326),
        ),
    ]
