# Generated by Django 4.2.7 on 2024-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0027_alter_adminboundaries_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='county',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sub_county',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sub_location',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
